steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/airflow:${_AIRFLOW_VERSION}',
        '-t', 'gcr.io/$PROJECT_ID/airflow',
        '--build-arg', 'AIRFLOW_VERSION=${_AIRFLOW_VERSION}',
        '.']


- name: 'gcr.io/$PROJECT_ID/airflow:${_AIRFLOW_VERSION}'
  id: Validation Test
  # Validate the integrity of the DAG files.
  entrypoint: python
  # env:
  # - AIRFLOW__CORE__DAGS_FOLDER=/workspace/${_DIRECTORY}/dags
  args:
  - -m
  - unittest
  - tests/sample_test.py
  

  # Deploy the DAGs to your composer environment DAGs GCS folder
- name: gcr.io/cloud-builders/gsutil
  id: Deploy SQL
  args:
    [ '-m',
    'rsync','-r', '-c','-x', '.*\.pyc|airflow_monitoring.py',
    'DataMart_Template/bigquery/',
    'gs://europe-west2-datamart-compo-d5ba1bb5-bucket/dags/sql/'
    ]
    
- name: gcr.io/cloud-builders/gsutil
  id: Deploy DAGs
  args:
  - -m
  - rsync
  - -r
  - -c
  - -x
  - .*\.pyc|airflow_monitoring.py
  - DataMart_Template/workflows/datamart1_dags/
  - gs://europe-west2-datamart-compo-d5ba1bb5-bucket/dags/

substitutions:
  _AIRFLOW_VERSION: 1.10.6

images:
  [ 'gcr.io/$PROJECT_ID/airflow:latest',
    'gcr.io/$PROJECT_ID/airflow:$_AIRFLOW_VERSION' 
  ]