# Deploy the DAGs to your composer environment DAGs GCS folder
steps:
- name: gcr.io/cloud-builders/gsutil
  id: Deploy DAGs
  args:
  - -m
  - rsync
  - -r
  - -c
  - -x
  - .*\.pyc|airflow_monitoring.py
  - DataMart_Template/workflows/datamart1_dags/sample_dag_v1_1_1.py
  - gs://europe-west2-datamart-compo-d5ba1bb5-bucket/dags/